object @leader
attributes :slug,
           :name,
           :title,
           :href,
           :photo_src,
           :prefix_name,
           :state_code,
           :born_on,
           :district,
           :residence,
           :spouse,
           :family,
           :religion,
           :website,
           :email,
           :twitter,
           :facebook,
           :webform,
           :member_status
